version: '3'
services:
  db:
    image: postgres
    container_name: jk5-db
    volumes:
      - ./mounts/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    user: '1000'
    networks:
      - elastic
    environment:
      POSTGRES_USER: uss
      POSTGRES_PASSWORD: usspw
      POSTGRES_DB: stockerize_prod

  elasticsearch:
    container_name: elasticsearch
    build:
      context: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic
    environment:
      - "discovery.type=single-node"
      - node.name=elasticsearch
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"

    volumes:
      - ./mounts/el_data:/usr/share/elasticsearch/data

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: jk5-app
    depends_on:
      - db
      - elasticsearch
    ports: 
      - "8080:8080"
    networks:
      - elastic
    volumes:
      - ${APPLICATION_ROOT_FOLDER}:/project
      - ${HOME}/.m2:/home/app/.m2

#  web:
##    image: tomcat:9
#    build:
#      context: ./tomcat
#    container_name: jk4-tomcat
#    ports: 
#      - "8080:8080"
#    links:
#       - app
#    depends_on:
#      - app
#      - db
#    networks:
#      - elk
#    volumes:
#      - ./target/apse-0.0.1-SNAPSHOT.jar:/usr/local/tomcat/webapps/apse.jar
#      - ./target/apse-0.0.1-SNAPSHOT:/usr/local/tomcat/webapps/apse      
      
networks:
  elastic:
    driver: bridge  
